### PR TITLE
converted install instructions from pdf to markdown, including images

### LINKED ISSUE #3: Rewrite the PDF documentation to Markdown
The documentation would be more accessible (through Google indexing) and for modification through the GitHub interface if it was written in [Markdown](https://help.github.com/articles/github-flavored-markdown/) instead of in a PDF file.

### PR DESCRIPTION
**Pull request by Sk8rSeth**
put images in the img/ directory and in the markdown they are referenced by relative path instead of full domain path.

I also recommend removing the contents section since its not relevant in markdown.

Fixes #3.

### CODE REVIEW

**Comment by asbjornu** [comment]
@Sk8rSeth: This is awesome! I agree that the index can be scrapped. I also think this PR can delete the PDF file, since the Markdown replaces it.

**Comment by Sk8rSeth** [comment]
alright, i removed both the old PDF as well as the contents section. hows that look?

**Comment by asbjornu** [comment]
Can you please get rid of the `.DS_Store` file? Otherwise this looks good!

**Comment by asbjornu** [comment]
Thank you! ❤️

**Pull request merged**
